benchmarks:
  - benchmark_name: ppermute
    benchmark_sweep_params:
      - {
          matrix_dim_range: { start: 1024, end: 20000, increase_by: 1024 },
          dtype: "bfloat16",
          dcn_size_range: 16,
          ici_size_range: 8,
        }
    warmup_tries: 10
    csv_path: "/tmp/microbenchmarks/collectives/csv"
    xlml_metrics_dir: "/tmp/microbenchmarks/collectives/xlml_metrics"
    csv_upload_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/csv"
    trace_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/trace"
    xlml_metrics_upload_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/xlml_metrics"
    xla_dump_upload_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/xla_dump"
  - benchmark_name: all_gather
    benchmark_sweep_params:
      - {
          matrix_dim_range: { start: 1024, end: 20000, increase_by: 1024 },
          dtype: "bfloat16",
          dcn_size_range: 16,
          ici_size_range: 8,
        }
    warmup_tries: 10
    csv_path: "/tmp/microbenchmarks/collectives/csv"
    xlml_metrics_dir: "/tmp/microbenchmarks/collectives/xlml_metrics"
    csv_upload_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/csv"
    trace_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/trace"
    xlml_metrics_upload_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/xlml_metrics"
    xla_dump_upload_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/xla_dump"
  - benchmark_name: psum
    benchmark_sweep_params:
      - {
          matrix_dim_range: { start: 1024, end: 20000, increase_by: 1024 },
          dtype: "bfloat16",
          dcn_size_range: 16,
          ici_size_range: 8,
        }
    warmup_tries: 10
    csv_path: "/tmp/microbenchmarks/collectives/csv"
    xlml_metrics_dir: "/tmp/microbenchmarks/collectives/xlml_metrics"
    csv_upload_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/csv"
    trace_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/trace"
    xlml_metrics_upload_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/xlml_metrics"
    xla_dump_upload_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/xla_dump"
  - benchmark_name: psum_scatter
    benchmark_sweep_params:
      - {
          matrix_dim_range: { start: 1024, end: 20000, increase_by: 1024 },
          dtype: "bfloat16",
          dcn_size_range: 16,
          ici_size_range: 8,
        }
    warmup_tries: 10
    csv_path: "/tmp/microbenchmarks/collectives/csv"
    xlml_metrics_dir: "/tmp/microbenchmarks/collectives/xlml_metrics"
    csv_upload_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/csv"
    trace_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/trace"
    xlml_metrics_upload_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/xlml_metrics"
    xla_dump_upload_dir: "gs://raymondlei-bugbash-bucket/microbenchmarks/outputs/tpu7x_8_16slice/xla_dump"
